name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build frontend container
        run: |
          docker build -t frontend -f ./frontend/Dockerfile ./frontend

      - name: Run tests in frontend container
        run: |
          docker run --rm frontend yarn test --watchAll=false
